name: Deploy Frontend

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build
        env:
            VITE_API_URL: ${{ secrets.VITE_API_URL }}
            VITE_API_URL_BASE: ${{ secrets.VITE_API_URL_BASE }}

      - name: Debug connection to server
        run: |
            sudo apt-get install -y traceroute
            echo "Runner IP:"
            curl -s ifconfig.me
            echo ""
            echo "DNS resolve:"
            nslookup ${{ secrets.SERVER_HOST }}
            echo ""
            echo "Testing SSH:"
            nc -zv ${{ secrets.SERVER_HOST }} 22 -w 10
            echo ""
            echo "Testing traceroute:"
            traceroute -m 15 ${{ secrets.SERVER_HOST }}

      - name: Deploy to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/home2/langbridge/www/"
          strip_components: 1
          rm: false

